source: image
save_result: False
fp16: False
experiment_name: AutoLabelTrack
name: bytetrack_tiny_track
exp_file: ./Tracking/exps/example/mot/yolox_l_vd.py #./Tracking/exps/default/yolox_l.py
ckpt: /home/leon/mount_point_c/data-track/labeltrack-models/yolox_l_best_ckpt.pth.tar  #./Tracking/weights/yolox_l_best_ckpt.pth.tar
device: gpu
fps: 30
track_thresh: 0.5
track_buffer: 30
match_thresh: 0.8
aspect_ratio_thresh: 1.6
min_box_area: 10
mot20: False

